// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQxDyNsrGMmUQuXjzeJ4T4K4WI1SOsfA',
    appId: '1:76823012149:android:858fa71b9bc24d2ae0a27c',
    messagingSenderId: '76823012149',
    projectId: 'tourist-guide-6f172',
    storageBucket: 'tourist-guide-6f172.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbZ8MPrjwkOdzsdpBN2MXLcjTdxg6sduI',
    appId: '1:76823012149:ios:402e1b8fc75bf4ede0a27c',
    messagingSenderId: '76823012149',
    projectId: 'tourist-guide-6f172',
    storageBucket: 'tourist-guide-6f172.firebasestorage.app',
    iosBundleId: 'com.example.touristGuide',
  );
}
